# Generated by Django 4.1.7 on 2023-02-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_githuburl_alter_contact_linkedinurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='githubUrl',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='linkedInUrl',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
