# Generated by Django 4.1.7 on 2023-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(blank='', default='', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.ImageField(blank='', default='', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
