# Generated by Django 4.1.7 on 2023-03-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('profile', models.ImageField(blank=True, default='', upload_to='me/')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('galery', models.ImageField(blank=True, default='', upload_to='me/')),
            ],
        ),
    ]
