# Generated by Django 4.1.7 on 2023-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='galery',
            field=models.ImageField(blank=True, default='', upload_to='me'),
        ),
        migrations.AlterField(
            model_name='me',
            name='profile',
            field=models.ImageField(blank=True, default='', upload_to='me'),
        ),
    ]
