# Generated by Django 4.1.7 on 2023-02-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('demoUrl', models.CharField(max_length=255)),
                ('githubUrl', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('technologies', models.JSONField()),
                ('languages', models.JSONField()),
                ('imageUrl', models.ImageField(upload_to='static/logos/')),
            ],
        ),
    ]
