# Generated by Django 4.1.7 on 2023-03-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('demo_url', models.CharField(max_length=255)),
                ('github_url', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('technologies', models.JSONField()),
                ('languages', models.JSONField()),
                ('image_url', models.ImageField(blank='', default='', upload_to='projects/')),
            ],
        ),
    ]
