# Generated by Django 4.1.7 on 2023-02-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demoUrl',
            new_name='demo_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='githubUrl',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
