# Generated by Django 4.1.7 on 2023-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(blank='', default='', upload_to='project'),
        ),
    ]
