# Generated by Django 4.1.7 on 2023-03-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_demourl_project_demo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(blank='', default='', upload_to='projects/'),
        ),
    ]
