# Generated by Django 4.1.7 on 2023-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='logoUrl',
            field=models.ImageField(upload_to='static/logos/company'),
        ),
    ]
