# Generated by Django 4.1.7 on 2023-03-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_logourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='logoUrl',
            field=models.ImageField(blank='', default='', upload_to='experiences/'),
        ),
    ]
