# Generated by Django 4.1.7 on 2023-03-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.ImageField(blank='', default='', upload_to='skills/')),
                ('experience', models.CharField(max_length=200)),
            ],
        ),
    ]
