# Generated by Django 4.1.7 on 2023-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo_url',
            field=models.ImageField(blank='', default='', upload_to='skill'),
        ),
    ]
